---
title: "Section 1: Data wrangling refresher"
format: html
---

```{r}
library(here)
library(janitor)
library(tidyverse)
library(sf)
library(kableExtra)
```

```{r}
# Load data
gdw_df <- read_csv(here("data", "gdw.csv")) %>%
  clean_names()
```

```{r}
# Data exploration
head(gdw_df, n = 10) |> 
  kable()

tail(gdw_df, n = 10) |> 
  kable()

dim(gdw_df)
names(gdw_df)
```

```{r}
 # Index, summarize, subset data
country_vec <- gdw_df[, "country"]
class(country_vec)

country_df <- gdw_df[["country"]]
class(country_df)

# count of dam types
dam_count <- gdw_df %>% 
  group_by(dam_type) %>% 
  summarize(dam_sum = n()) 

# create subset
sub_dam <- gdw_df %>% 
  filter(dam_type == "Dam")

# reorder by installation year
by_year <- gdw_df %>% 
  arrange(year_dam)
```

```{r}
# Data visualization 
gdw_df |>
  group_by(country) |>
  summarize(mean_dam_hgt_m = mean(dam_hgt_m, na.rm = TRUE)) |>
  ungroup() |> 
  ggplot(aes(x = country, y = mean_dam_hgt_m)) +
    geom_bar(stat = "identity") +
    labs(x = "Country",
         y = "Average height of dam/barrier in meters") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1))

```

```{r}
ggplot(data = gdw_df,
      aes(x = cap_mcm, y = dam_hgt_m)) +
  geom_point() +
  labs(x = "Storage capacity of reservoir in million cubic meters",
       y = "Height of dam/barrier in meters") +
  theme_minimal()
```

```{r}
head(gdw_df$shape, n = 3)

class(gdw_df$shape)

gdw_st <- st_read(here("data", "gdw.gdb")) |>
  clean_names() # Convert variable names to lower snake case

gdw_sf <- read_sf(here("data", "gdw.gdb")) |>
  clean_names() # Convert variable names to lower snake case
```

